# Original scaffold (auto-generated by rails-backbone)...
# class Chlite.Routers.SearchesRouter extends Backbone.Router
#   initialize: (options) ->
#     @searches = new Chlite.Collections.SearchesCollection()
#     @searches.reset options.searches

#   routes:
#     "new"      : "newSearch"
#     "index"    : "index"
#     ":id/edit" : "edit"
#     ":id"      : "show"
#     ".*"        : "index"

#   newSearch: ->
#     @view = new Chlite.Views.Searches.NewView(collection: @searches)
#     $("#searches").html(@view.render().el)

#   index: ->
#     @view = new Chlite.Views.Searches.IndexView(searches: @searches)
#     $("#searches").html(@view.render().el)

#   show: (id) ->
#     search = @searches.get(id)

#     @view = new Chlite.Views.Searches.ShowView(model: search)
#     $("#searches").html(@view.render().el)

#   edit: (id) ->
#     search = @searches.get(id)

#     @view = new Chlite.Views.Searches.EditView(model: search)
#     $("#searches").html(@view.render().el)

# class Chlite.Routers.SearchesRouter extends Backbone.Router
#   initialize: (options) ->
#     # @search = new Chlite.Models.Search()
#     # @search.reset options.search #Hmm this might be wrong...

#   routes:
#     ".*" : "show"

#   show: ->
#     @view = new Chlite.Views.Searches.ShowView(model: @search)
#     $('#searches').html(@view.render().el)

class Chlite.Routers.SearchesRouter extends Backbone.Router
  initialize: (options) ->
    @search = new Chlite.Collections.Search()
    @search.reset options.campsites #Hmm this might be wrong...
    @zoom = options.zoom
    @distance = options.distance
    @keywords = options.keywords
    @center = options.center

  routes:
    ".*" : "show"

  show: ->
    @view = new Chlite.Views.Searches.ShowView(search: @search)


